spring.application.name=hydrogen-ingestion-engine

spring.threads.virtual.enabled=true

spring.ai.openai.api-key=${OPENROUTER_API_KEY:}

spring.ai.openai.chat.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=google/gemini-2.5-flash
spring.ai.openai.chat.temperature=0.1

# настройки промышленной шины (MQTT И INFLUXDB)
industrial.mqtt.broker-url=tcp://localhost:1883
industrial.mqtt.client-id=java-ingestion-engine-client
industrial.mqtt.topic=hydrogen/telemetry/+

industrial.influxdb.url=http://localhost:8086
industrial.influxdb.token=${INFLUXDB_TOKEN:default_secure_token}    HydrogenSuperPassword2026
industrial.influxdb.org=hydrogen_hub
industrial.influxdb.bucket=telemetry_bucket

logging.level.root=INFO
logging.level.org.springframework.integration=WARN
logging.level.com.hydrogen.engine=DEBUG
